rules: ({
  match = "(class_g = 'st-256color' || class_g = 'Emacs')"
          " && focused";
  opacity = 0.7;
}, {
  match = "(class_g = 'st-256color' || class_g = 'Emacs')"
          " && !focused";
  opacity = 0.7;
})
