rules: ({
  match = "(class_g = 'st-256color' || class_g = 'Emacs' || class_g = 'kitty' || class_g = 'alacritty')"
          " && focused";
  opacity = 0.8;
}, {
  match = "(class_g = 'st-256color' || class_g = 'Emacs' || class_g = 'kitty' || class_g = 'alacritty')"
          " && !focused";
  opacity = 0.8;
})
